### ISSUE TITLE
Support mjs files as entrypoints

### ISSUE THREAD

**Issue by SaschaSchwarze0** [paketo-buildpacks/node-start#225]
The node-start buildpack at the moment looks just for js files as start scripts, https://github.com/paketo-buildpacks/node-start/blob/v0.8.1/node_application_finder.go#L32. If I use ECMAScript modules and therefore `import` statements and name my file with mjs as extension, then it won't work.

A sample code repository that today cannot be built is https://github.com/SaschaSchwarze0/dump-headers.

## Describe the Enhancement

Extend node-start to also look at mjs files.

## Possible Solution

This must be extended at those places:

- https://github.com/paketo-buildpacks/node-start/blob/v0.8.1/node_application_finder.go#L32
- https://github.com/paketo-buildpacks/paketo-website/blob/main/content/docs/howto/nodejs.md

## Motivation

Adoption of ECMAScript modules is growing.

**Comment by mhdawson** [comment]
I can take a look at this as a follow on to https://github.com/paketo-buildpacks/libnodejs/pull/8

@SaschaSchwarze0 is your suggestion just that it looks for the same files with an mjs extension in addition to the .js ones ?

One question is also how it should affect the ordering.  My first take would be same ordering in terms of server, app etc. but look for both `.js` and `.mjs` for each before moving to the next.  Does that make sense to you?

**Comment by SaschaSchwarze0** [comment]
> One question is also how it should affect the ordering. My first take would be same ordering in terms of server, app etc. but look for both `.js` and `.mjs` for each before moving to the next. Does that make sense to you?

Makes sense, yes. Thank you.

**Comment by mhdawson** [comment]
@nodejs/maintainers does what I outlined in https://github.com/paketo-buildpacks/node-start/issues/225#issuecomment-1532024712 sound good to you? If so I'll submit a PR once some of the existing ones I have open land.

**Comment by mhdawson** [comment]
opps wrong mention

@paketo-buildpacks/nodejs-maintainers does what I outlined in https://github.com/paketo-buildpacks/node-start/issues/225#issuecomment-1532024712 sound good to you? If so I'll submit a PR once some of the existing ones I have open land.

**Comment by c0d1ngm0nk3y** [comment]
> A sample code repository that today cannot be built is https://github.com/SaschaSchwarze0/dump-headers.

But can't you simple add the environment variable `BP_LAUNCHPOINT=server.mjs`. Works for me.

**Comment by SaschaSchwarze0** [comment]
> > A sample code repository that today cannot be built is https://github.com/SaschaSchwarze0/dump-headers.
> 
> But can't you simple add the environment variable `BP_LAUNCHPOINT=server.mjs`. Works for me.

Yep, this is more about what works ootb without that you must customize something. Is imo hard to explain that you evolve your app to modules, by that use mjs as extension and suddenly the build does not work anymore (without env customization).

**Comment by mhdawson** [comment]
This dropped off my radar, will try to get back to it.

**Comment by mhdawson** [comment]
Submitted - https://github.com/paketo-buildpacks/libnodejs/pull/31 as the first step. Once that lands we can add some additional testing into this buildpack to validate the .mjs cases.
