### ISSUE TITLE
The buildpack should only detect when there is a server.js file

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/node-start#26]
The buildpack currently detects if there is any `*.js` file in the `/workspace`:
https://github.com/paketo-buildpacks/node-start/blob/fabe54baf1f7f3e4fc0933a442de7283480484ad/detect.go#L11-L17

This means that the app successfully builds, but then fails when the user tries to run the image. This feedback mechanism seems a bit obtuse. Could we not fail during detection with a message that would give the user that same feedback?

In addition, we should look during detection for other possibly common names for entrypoints, maybe `app.js`, `main.js`, `index.js` in addition to `server.js`. If there is a match, then we can use that filename. In all other cases, we'd fail during detection.

**Comment by qu1queee** [comment]
@ryanmoran hi, does this have an ETA? If I understand the issue correctly, this will make the build to fail and prevent users to go ahead and deploy something that will eventually fail.
