### ISSUE TITLE
Implement support for BP_LAUNCHPOINT  as described in RFC 0003

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/node-start#58]
Requesting implementation of relevant sections of [RFC 0003](https://github.com/paketo-buildpacks/nodejs/blob/main/rfcs/0003-buildpack-yml-to-env-var.md) that lets users migrate to environment variables from buildpack.yml for buildpack configurations.

The buildpack should support:
* BP_LAUNCHPOINT

**Comment by arjun024** [comment]
@fg-j If we have to account for `BP_LAUNCHPOINT` being set by a preceding buildpack (like you mentioned in another conversation), we should be pretty liberal in detect and not fail or error, but maybe pass with a warning printed in logs. What do you think? I feel like `BP_GO_TARGETS` in go buildpacks and this should have similar behavior.
@thitch97 @ForestEckhardt Any thoughts?

**Comment by thitch97** [comment]
@arjun024 and I have decided that it is suitable to fail detection when `BP_LAUNCHPOINT` is invalid. We don't think it will be too confusing for the end user given the resulting error.

**Comment by fg-j** [comment]
Tested out this feature with the [no-package-manager sample app](https://github.com/paketo-buildpacks/samples/tree/a8ae9370b82fe427c274321acd32f7e0a16ae253/nodejs/no-package-manager). **Except I created a `src` directory and moved `server.js` to `src/myfile.js`.**

So the app structure is:
```
.
|-- README.md
`-- src
    `-- myfile.js
```

And `myfile.js` is a simple node server.

When I build using:
```
pack build nodejs-sample-nested  /
--buildpack gcr.io/paketo-buildpacks/node-engine:0.2.2  /
--buildpack gcr.io/paketo-buildpacks/node-start:0.1.0 /
--env BP_LAUNCHPOINT=src/myfile.js
```

In the build logs, see that the Node Start buildpack sets the start command of my app correctly:
```
[builder] Paketo Node Start Buildpack 0.1.0
[builder]   Assigning launch processes
[builder]     web: node src/myfile.js
```

And the app successfully runs and serves the desired content!
